# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
<<<<<<< HEAD
  secret_key_base: bdb10bc8a8b7897553d3e8923b35a288affa2740f8f07f8281e631cf1e6d0bdf3fff47a8bddebc4b2c89dee25ed15f6cc68a3c0ce0659fdd165d8c98d8d38dc5

test:
  secret_key_base: fbe46d20262d43196070aff6b7eb7ef13034e81ad637780e7c67e7ee471b718c59b1f9a4c2ce9b912836f89b23a99440a5ae085bf6280ff30aeae1a4f52d873c
=======
  secret_key_base: 129cbb8b0d8d19b94b5e14f1ae3427c2c220c78fb46779a0bea41105d489b109a1314e2c6d701c815e92da7b1132f6e051a6765867e7db2056a92cc994369d08

test:
  secret_key_base: bd13db0a2bffc21e00ec53844142781e7064a5d2eb0dadb65a943d8d6a03a4b0619d020b09fb7419b73cf4dcbec6eb7a48cbae45008f1aab57eed371aff15fe5
>>>>>>> fd31c8cfa51fdee45960d86fa085cefc2ebef888

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
